export { ComparisonProvider, FloatingCompareBar, useComparison } from './ComparisonBar'
export { addComparisonProject, createComparisonSession, mergeComparisonProjects, normalizeComparisonIds, removeComparisonProject, reorderComparisonProject, replaceComparisonProject, saveComparisonSession, updateComparisonProjects } from './session'
export { buildComparisonMatrix, type ComparisonCell, type ComparisonDimension, type ComparisonDimensionId, type ComparisonRow } from './matrix'
export { completeDecisionDraft, createDecisionDraft, deserializeDecisionDraft, serializeDecisionDraft, type DecisionDraft } from './decision'
export { DecisionForm, affectedFieldLabels, decisionActionLabels } from './DecisionForm'
