import { expect, test } from '@playwright/test'

test.describe('T55 键盘与焦点', () => {
  test('Modal 和 Drawer 限制焦点并在关闭后恢复触发点', async ({ page, isMobile }) => {
    test.skip(isMobile, '桌面执行一次焦点循环；移动比较另有键盘用例')
    await page.goto('/project/project-pdfquizlab')

    const favorite = page.locator('.project-primary-actions').getByRole('button', { name: '收藏' })
    await favorite.focus()
    await page.keyboard.press('Enter')
    const modal = page.getByRole('dialog', { name: '登录后继续刚才的操作' })
    await expect(modal).toBeVisible()
    await expect.poll(() => page.evaluate(() => document.querySelector('[role="dialog"]')?.contains(document.activeElement))).toBe(true)

    await page.keyboard.press('Shift+Tab')
    await expect.poll(() => page.evaluate(() => document.querySelector('[role="dialog"]')?.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Tab')
    await expect(modal.getByRole('button', { name: '关闭弹层' })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(modal).toBeHidden()
    await expect(favorite).toBeFocused()

    const evidenceTrigger = page.getByRole('button', { name: /展开本作品证据/ }).first()
    await evidenceTrigger.focus()
    await page.keyboard.press('Enter')
    const drawer = page.getByRole('dialog', { name: '事实来源与核验记录' })
    await expect(drawer).toBeVisible()
    await expect.poll(() => page.evaluate(() => document.querySelector('.drawer-panel')?.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(drawer).toBeHidden()
    await expect(evidenceTrigger).toBeFocused()
  })

  test('键盘完成搜索加入比较、决策和登录续办', async ({ page, isMobile }) => {
    test.skip(isMobile, '移动端同一决策在 comparison-mobile.spec.ts 覆盖')
    const idea = '我想把大学 PDF 讲义生成选择题'
    await page.goto(`/search?q=${encodeURIComponent(idea)}&mode=similar`)
    await page.getByRole('link', { name: /确认完整意图/ }).focus()
    await page.keyboard.press('Enter')
    await page.getByRole('button', { name: '确认并查看同类分析' }).focus()
    await page.keyboard.press('Enter')

    const candidate = page.locator('article').filter({ has: page.locator('a[href="/project/project-papertopractice"]') })
    const addButton = candidate.getByRole('button', { name: '加入比较' })
    await addButton.focus()
    await page.keyboard.press('Enter')
    await expect(candidate.getByRole('button', { name: '移出比较' })).toHaveAttribute('aria-pressed', 'true')
    const compareLink = page.getByRole('link', { name: '开始比较' })
    await compareLink.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: '比较会话' })).toBeVisible()

    await page.getByRole('radio', { name: '调整' }).focus()
    await page.keyboard.press('Space')
    await page.getByRole('checkbox', { name: '定位' }).focus()
    await page.keyboard.press('Space')
    const reason = page.getByLabel('判断理由')
    await reason.focus()
    await page.keyboard.insertText('根据同类差异调整目标用户与产品定位。')
    const save = page.getByRole('button', { name: '完成并私密保存' })
    await save.focus()
    await page.keyboard.press('Enter')

    const login = page.getByRole('dialog', { name: '登录后继续刚才的操作' })
    await expect(login).toBeVisible()
    const mia = login.getByRole('button', { name: /米娅/ })
    await mia.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: '决策记录已保存' })).toBeVisible()
  })

  test('键盘进入发布表单，校验错误与控件建立关联', async ({ page, isMobile }) => {
    test.skip(isMobile, '响应式发布流程已在 T54 覆盖，这里验证键盘语义')
    await page.goto('/auth?from=%2Fsubmit')
    const login = page.getByRole('button', { name: '使用米娅测试身份' })
    await login.focus()
    await page.keyboard.press('Enter')
    await expect(page).toHaveURL(/\/submit$/)

    const url = page.getByRole('textbox', { name: /^作品地址/ })
    await url.focus()
    await page.keyboard.insertText('https://example.test/keyboard-publish')
    const check = page.getByRole('button', { name: '检查地址' })
    await check.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByText('地址检查通过')).toBeVisible()
    const continueButton = page.getByRole('button', { name: '继续自动预填' })
    await continueButton.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: '发布新作品' })).toBeVisible()
    await expect(page.getByRole('button', { name: '保存并继续' })).toBeVisible()

    const definition = page.getByLabel('一句话定义')
    await definition.fill('')
    const next = page.getByRole('button', { name: '保存并继续' })
    await next.focus()
    await page.keyboard.press('Enter')
    await expect(definition).toBeFocused()
    await expect(definition).toHaveAttribute('aria-invalid', 'true')
    await expect(definition).toHaveAttribute('aria-describedby', 'submission-definition-error')
    await expect(page.locator('#submission-definition-error')).toHaveAttribute('role', 'alert')
  })

  test('移动比较标签支持方向键和 roving tabindex', async ({ page, isMobile }) => {
    test.skip(!isMobile, '仅移动端显示作品标签')
    await page.goto('/compare/comparison-anonymous-pdf')
    const tabs = page.getByRole('tablist', { name: '移动端作品切换' })
    const first = tabs.getByRole('tab').first()
    const second = tabs.getByRole('tab').nth(1)
    await first.focus()
    await page.keyboard.press('ArrowRight')
    await expect(second).toBeFocused()
    await expect(second).toHaveAttribute('aria-selected', 'true')
    await expect(first).toHaveAttribute('tabindex', '-1')
    await page.keyboard.press('Home')
    await expect(first).toBeFocused()
    await expect(first).toHaveAttribute('tabindex', '0')
  })
})
