import { expect, test } from '@playwright/test'
import { installMockAuth } from './support/mock-auth'

test.describe('T55 键盘与焦点', () => {
  test('Modal 和 Drawer 限制焦点并在关闭后恢复触发点', async ({ page, isMobile }) => {
    test.skip(isMobile, '桌面执行一次焦点循环；移动比较另有键盘用例')
    await page.goto('/project/project-pdfquizlab')

    const favorite = page.locator('.project-primary-actions').getByRole('button', { name: '收藏' })
    await favorite.focus()
    await page.keyboard.press('Enter')
    const modal = page.getByRole('dialog', { name: '登录后继续刚才的操作' })
    await expect(modal).toBeVisible()
    await expect.poll(() => page.evaluate(() => document.querySelector('[role="dialog"]')?.contains(document.activeElement))).toBe(true)

    await page.keyboard.press('Shift+Tab')
    await expect.poll(() => page.evaluate(() => document.querySelector('[role="dialog"]')?.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Tab')
    await expect(modal.getByRole('button', { name: '关闭弹层' })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(modal).toBeHidden()
    await expect(favorite).toBeFocused()

    const evidenceTrigger = page.getByRole('button', { name: /展开本作品证据/ }).first()
    await evidenceTrigger.focus()
    await page.keyboard.press('Enter')
    const drawer = page.getByRole('dialog', { name: '事实来源与核验记录' })
    await expect(drawer).toBeVisible()
    await expect.poll(() => page.evaluate(() => document.querySelector('.drawer-panel')?.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(drawer).toBeHidden()
    await expect(evidenceTrigger).toBeFocused()
  })

  test('键盘完成搜索、加入比较并查看所选作品差异', async ({ page, isMobile }) => {
    test.skip(isMobile, '移动端比较在 comparison-mobile.spec.ts 覆盖')
    const idea = '我想把大学 PDF 讲义生成选择题'
    await page.goto('/projects')
    const search = page.getByRole('banner').getByRole('search')
    const input = search.getByRole('textbox', { name: '搜索作品或输入完整想法' })
    await input.focus()
    await page.keyboard.insertText(idea)
    await search.getByRole('button', { name: '搜索' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: '一起把想法说清楚' })).toBeVisible()
    await page.getByRole('button', { name: '确认并查找相似作品' }).focus()
    await page.keyboard.press('Enter')

    const candidate = page.locator('article').filter({ has: page.locator('a[href="/project/project-papertopractice"]') })
    const addButton = candidate.getByRole('button', { name: '加入比较' })
    await addButton.focus()
    await page.keyboard.press('Enter')
    await expect(candidate.getByRole('button', { name: '移出比较' })).toHaveAttribute('aria-pressed', 'true')
    const compareLink = page.getByRole('link', { name: '开始比较' })
    await compareLink.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: '比较会话' })).toBeVisible()

    const reveal = page.getByRole('button', { name: '查看完整字段' })
    await reveal.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('navigation', { name: '比较维度' })).toBeVisible()
    await expect(page.getByText(/当前仅比较你选择的 \d+ 个作品/)).toBeVisible()
    await expect(page.getByRole('heading', { name: '记录比较后的行动' })).toHaveCount(0)
  })

  test('键盘进入发布表单，校验错误与控件建立关联', async ({ page, isMobile }) => {
    test.skip(isMobile, '响应式发布流程已在 T54 覆盖，这里验证键盘语义')
    await installMockAuth(page, { submission: true })
    await page.goto('/auth?return_to=%2Fsubmit')
    const email = page.getByRole('textbox', { name: '邮箱地址' })
    await email.focus()
    await page.keyboard.insertText('mia@example.test')
    const sendCode = page.getByRole('button', { name: '发送验证码' })
    await sendCode.focus()
    await page.keyboard.press('Enter')
    const otp = page.getByRole('textbox', { name: '6 位验证码' })
    await expect(otp).toBeVisible()
    await otp.focus()
    await page.keyboard.insertText('123456')
    const verify = page.getByRole('button', { name: '验证并登录' })
    await verify.focus()
    await page.keyboard.press('Enter')
    await expect(page).toHaveURL(/\/submit$/)

    const url = page.getByRole('textbox', { name: /^作品地址/ })
    await url.focus()
    await page.keyboard.insertText('https://example.test/keyboard-publish')
    const check = page.getByRole('button', { name: '检查地址' })
    await check.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByText('地址检查通过')).toBeVisible()
    const continueButton = page.getByRole('button', { name: '继续补充作品信息' })
    await continueButton.focus()
    await page.keyboard.press('Enter')
    const submissionRail = page.getByRole('navigation', { name: '发布步骤' })
    await expect(submissionRail.locator('[aria-current="step"]')).toHaveText('基础信息')
    await expect(page.getByRole('button', { name: '保存并继续' })).toBeVisible()

    const name = page.getByRole('textbox', { name: '作品名称' })
    await name.focus()
    await page.keyboard.insertText('键盘发布作品')
    const definition = page.getByLabel('一句话定义')
    await definition.fill('')
    const next = page.getByRole('button', { name: '保存并继续' })
    await next.focus()
    await page.keyboard.press('Enter')
    await expect(definition).toHaveAttribute('aria-invalid', 'true')
    await expect(definition).toHaveAttribute('aria-describedby', 'submission-definition-error')
    await expect(page.locator('#submission-definition-error')).toHaveAttribute('role', 'alert')
    const errorSummaryLink = page.getByRole('link', { name: '一句话定义' })
    await expect(errorSummaryLink).toBeVisible()
    await errorSummaryLink.focus()
    await page.keyboard.press('Enter')
    await expect(definition).toBeFocused()
  })

  test('移动比较标签支持方向键和 roving tabindex', async ({ page, isMobile }) => {
    test.skip(!isMobile, '仅移动端显示作品标签')
    await page.goto('/compare/comparison-anonymous-pdf')
    await page.getByRole('button', { name: '查看完整字段' }).click()
    const tabs = page.getByRole('tablist', { name: '移动端作品切换' })
    const first = tabs.getByRole('tab').first()
    const second = tabs.getByRole('tab').nth(1)
    await first.focus()
    await page.keyboard.press('ArrowRight')
    await expect(second).toBeFocused()
    await expect(second).toHaveAttribute('aria-selected', 'true')
    await expect(first).toHaveAttribute('tabindex', '-1')
    await page.keyboard.press('Home')
    await expect(first).toBeFocused()
    await expect(first).toHaveAttribute('tabindex', '0')
  })
})
