import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('publication sections, validation, frozen metadata and public detail work on desktop and mobile', async ({ page, isMobile }, testInfo) => {
  await page.setViewportSize({ width: isMobile ? 360 : 1280, height: 900 })
  const start = '/submit?category=personal_site_portfolio&scenario=review_approved'
  await page.goto(`/auth?from=${encodeURIComponent(start)}`)
  await page.getByRole('button', { name: '使用米娅账号' }).click()
  await page.getByRole('textbox', { name: /^作品地址/ }).fill('https://example.test/publication-ready-portfolio')
  await page.getByRole('button', { name: '检查地址' }).click()
  await page.getByRole('button', { name: '继续补充作品信息' }).click()
  await expect(page.getByRole('textbox', { name: '作品名称' })).toHaveValue('自动提取的作品名称')
  await page.getByRole('textbox', { name: '作品名称' }).fill('小岛作品集')
  await page.getByLabel('提交者关系（必填）').selectOption('team_member')
  await page.getByRole('textbox', { name: '所属团队或开发者（可跳过）' }).fill('小岛团队')
  await page.getByRole('textbox', { name: 'Logo 地址（可跳过）' }).fill('https://example.test/logo.png')
  await page.getByRole('textbox', { name: '作品封面地址（可跳过）' }).fill('https://example.test/cover.png')

  await page.getByRole('link', { name: '最终预览' }).click()
  await expect(page.getByRole('button', { name: '确认并提交审核' })).toBeDisabled()
  await page.getByRole('link', { name: '修改创作者身份' }).click()
  await page.getByRole('checkbox', { name: '开发者' }).check()
  await page.getByRole('checkbox', { name: '展示项目' }).check()
  await page.getByRole('textbox', { name: '详细介绍（可跳过）' }).fill('展示公开开发项目和可复用组件。')
  await page.getByRole('textbox', { name: '图集地址（可跳过，每行一张）' }).fill('https://example.test/page-one.png\nhttps://example.test/page-two.png')
  await page.getByRole('textbox', { name: '产品视频（可跳过）' }).fill('https://www.bilibili.com/video/BV1example')
  await page.getByRole('link', { name: '3 核心内容' }).click()
  await page.getByRole('checkbox', { name: '项目', exact: true }).check()
  await page.getByRole('link', { name: '4 开发与资产' }).click()
  await page.getByRole('button', { name: '添加致谢' }).click()
  await page.getByRole('textbox', { name: '致谢 1 名称' }).fill('公开组件库')
  await page.getByRole('textbox', { name: '致谢 1 说明' }).fill('帮助实现项目展示模块。')
  await page.getByRole('button', { name: '保存并预览' }).click()
  await expect(page.getByRole('button', { name: '确认并提交审核' })).toBeEnabled()
  await expect(page.getByRole('button', { name: '查看详情图 2 ↗' })).toBeVisible()
  while (await page.getByRole('button', { name: '关闭提示' }).count()) {
    await page.getByRole('button', { name: '关闭提示' }).first().click()
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(accessibility.violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('publication-preview.png'), fullPage: true })

  await page.getByRole('button', { name: '确认并提交审核' }).click()
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  await expect(page.getByRole('heading', { name: '审核状态：已通过' })).toBeVisible()
  await page.getByRole('link', { name: '进入作品详情' }).click()
  await expect(page.getByRole('heading', { name: '小岛作品集', level: 1 })).toBeVisible()
  await expect(page.getByText('展示公开开发项目和可复用组件。')).toBeVisible()
  await expect(page.getByText('帮助实现项目展示模块。')).toBeVisible()
  await expect(page.getByText('尚未关联作者', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('展示公开开发项目和可复用组件。')).toBeVisible()
})
